# Generated by Django 5.1.7 on 2025-04-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='testimonial',
        ),
    ]
